import type { Metadata } from 'next';
import { Karla, Merriweather, Geist_Mono } from 'next/font/google';
import './globals.css';
import Footer from '@/components/footer';

// Body copy
const karla = Karla({
  subsets: ['latin'],
  variable: '--font-karla',
  weight: ['300', '400', '500', '600', '700'],
});

// Headings
const merriweather = Merriweather({
  subsets: ['latin'],
  variable: '--font-merriweather',
  weight: ['300', '400', '700', '900'],
  style: ['normal', 'italic'],
});

// Optional monospace for code blocks
const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${karla.variable} ${merriweather.variable} ${geistMono.variable} antialiased`}
      >
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
